version: '3.2'
services:
  api:
    container_name:  "${APP_NAME}-nodejs"
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./docker-start.sh
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "3333:3333"
    networks:
      - default
    depends_on:
      - postgres
  postgres:
    container_name: "${APP_NAME}-postgres"
    image: postgres:12.0-alpine
    volumes:
      - "./data/:/var/lib/postgres"
      #dump dir for production import
      - "./dump/:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_PASSWORD}"

#define network
networks:
  default:
    driver: bridge